# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

name: lint

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::lintr, local::.
          needs: lint

      - name: Lint
        run: |
          lintr::lint_package(
            linters = lintr::linters_with_defaults(
              line_length_linter = lintr::line_length_linter(120),
              cyclocomp_linter = lintr::cyclocomp_linter(15),
              object_name_linter = lintr::object_name_linter(c('snake_case'))
            )
          )
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true
          LINTR_COMMENT_BOT: true
